### ISSUE TITLE
Where is the dataset and code?

### ISSUE THREAD

**Issue by Syize** [kaka0910/M4Fog#1]
I occasionally read the [paper](https://arxiv.org/html/2406.13317v1) in arXiv, which gives the url to this repo. But I can't find any dataset or code in this repo.

**Comment by kaka0910** [comment]
Thank you for your interest in our work. Our M4Fog dataset and code will be released soon, and we will respond to you immediately at that time.

**Comment by kaka0910** [comment]
@Syize We have updated the data and code in the repository, and you are welcome to use and download our data. If you have any questions, please contact us in time.
